name: "SimplePBI-Ops"
description: "GitHub Action to handle Power BI Projects CICD using SimplePBI Python library."
author: "Ignacio Barrau"

inputs:
  tenant_id:
    description: "Azure Tenant ID"
    required: true
  app_id:
    description: "Azure App ID"
    required: true
  secret_key:
    description: "Azure Secret Key"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install simplepbi
      shell: bash

    - name: Detect changed folders
      id: detect_changes
      run: |
        # Define the folder to check for changes
        target_folder="Workspaces/"
      
        # Get changed folders
        changed_folders=$(git diff --name-only HEAD^..HEAD -- "$target_folder" | \
          grep -vE '\.pbip$' | \
          sed 's|/[^/]*$||' | sort | uniq)
      
        # Filter only existing folders
        existing_folders=""
        while IFS= read -r folder; do
          if [ -d "$folder" ]; then
            existing_folders+="$folder"$'\n'
          fi
        done <<< "$changed_folders"
      
        # Remove trailing newline and convert to comma-separated list
        existing_folders=$(echo "$existing_folders" | sed '/^\s*$/d' | paste -sd "," -)
      
        echo "changed_folders=$existing_folders" >> $GITHUB_ENV
        echo "Changed folders: $existing_folders"
      shell: bash

    - name: Run Python script
      run: |
        python ldw-deploy.py "ldw-key" "${{ inputs.tenant_id }}" "${{ inputs.app_id }}" "${{ inputs.secret_key }}" "$changed_folders"
      shell: bash
